# # Workflow name
# name: "workflow pm2 configuration"

# # Event, trigger action that running our Jobs.
# # In this file we trigger pm2-configuration every we push code to repository.
# on: [push]
# jobs:
#   pm2-configuration:
#     # Runner, This job will be running in runner with Ubuntu Server latest version.
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3 # Checkout code from repository, so we code downloaded in runner.
#       - uses: actions/setup-node@v3 # Setup nodejs in our runner
#       - run: npm install pm2@latest -g # Install pm2 global
#       - run: pm2 -V # Check pm2 version
#       - run: pm2 list # Check pm2 list
#       # Running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
#       - run: pm2 start index.js --watch -i max